/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.jw.service.gui;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import org.jw.service.action.DefaultCloseAction;
import org.jw.service.action.DefaultPrintAction;
import org.jw.service.dao.DataAccessObject;
import org.jw.service.entity.AppsReport;
import org.jw.service.factory.DefaultParameterListFactory;
import org.jw.service.print.PrintParameter;
import org.jw.service.util.UtilityDatabase;
import org.jw.service.util.UtilityReportPrint;

/**
 *
 * @author Wilson
 */
public class ReportPrintDialog extends javax.swing.JDialog {

    private final EntityManager em;
    
    
    /**
     * Creates new form ReportPrintDialog
     */
    public ReportPrintDialog(java.awt.Frame parent, boolean modal, EntityManager em, UtilityReportPrint utilPrint) {
        super(parent, modal);
        this.em = em;
        this.utilDB = UtilityDatabase.create(em);
        this.utilPrint = utilPrint;
        initComponents();
        initMyComponents();
    }
    
    private void initMyComponents(){
        DataAccessObject<AppsReport> dao = DataAccessObject.create(em, AppsReport.class);        
        Query query = em.createNamedQuery("AppsReport.findEnableAndVisible", AppsReport.class);
        query.setParameter("enable", Boolean.TRUE);
        query.setParameter("visible", Boolean.TRUE);
        List<AppsReport> list = query.getResultList();
        this.reportsComboBox.setModel(new DefaultComboBoxModel(list.toArray()));                
        this.printAction = new DefaultPrintAction(printCommand, reportsComboBox, utilPrint, printParametersList);
        this.closeAction = new DefaultCloseAction(cancelCommand, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        printParametersList = org.jdesktop.observablecollections.ObservableCollections.observableList(new java.util.ArrayList<org.jw.service.print.PrintParameter>());
        reportLabel = new javax.swing.JLabel();
        reportsComboBox = new javax.swing.JComboBox();
        cancelCommand = new javax.swing.JButton();
        printCommand = new javax.swing.JButton();
        parametersPanel = new javax.swing.JPanel();
        parameterrsScrollPane = new javax.swing.JScrollPane();
        parametersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jw/service/gui/resources/properties/dialog_titles"); // NOI18N
        setTitle(bundle.getString("report.print.dialog.title")); // NOI18N
        setResizable(false);

        reportLabel.setText("Report:");

        reportsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsComboBoxActionPerformed(evt);
            }
        });

        cancelCommand.setText("Cancel");

        printCommand.setText("Print Preview");

        parametersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parameters", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        parametersTable.setRowHeight(27);
        parametersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        parametersTable.getTableHeader().setReorderingAllowed(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, printParametersList, parametersTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${label}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${value}"));
        columnBinding.setColumnName("Value");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        parameterrsScrollPane.setViewportView(parametersTable);
        if (parametersTable.getColumnModel().getColumnCount() > 0) {
            parametersTable.getColumnModel().getColumn(0).setResizable(false);
            parametersTable.getColumnModel().getColumn(0).setCellRenderer(org.jw.service.table.cell.renderer.DefaultStateCellRenderer.create());
            parametersTable.getColumnModel().getColumn(1).setResizable(false);
            parametersTable.getColumnModel().getColumn(1).setCellEditor(org.jw.service.table.cell.editor.DefaultDataTypeCellEditor.create(printParametersList));
        }

        javax.swing.GroupLayout parametersPanelLayout = new javax.swing.GroupLayout(parametersPanel);
        parametersPanel.setLayout(parametersPanelLayout);
        parametersPanelLayout.setHorizontalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parameterrsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
        parametersPanelLayout.setVerticalGroup(
            parametersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parameterrsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(printCommand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelCommand))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reportLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reportsComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(parametersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reportsComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(reportLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(parametersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelCommand)
                    .addComponent(printCommand))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsComboBoxActionPerformed
        // TODO add your handling code here:
        AppsReport report = (AppsReport) this.reportsComboBox.getSelectedItem();
        List<PrintParameter> paramList = DefaultParameterListFactory.create(new ArrayList(report.getAppsReportParameterCollection()));
        printParametersList.clear();
        printParametersList.addAll(paramList);
    }//GEN-LAST:event_reportsComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelCommand;
    private javax.swing.JScrollPane parameterrsScrollPane;
    private javax.swing.JPanel parametersPanel;
    private javax.swing.JTable parametersTable;
    private javax.swing.JButton printCommand;
    private java.util.List<org.jw.service.print.PrintParameter> printParametersList;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JComboBox reportsComboBox;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private UtilityDatabase utilDB;
    private UtilityReportPrint utilPrint;
    private DefaultPrintAction printAction;
    private DefaultCloseAction closeAction;
}


